bert_params:
  model_name_or_path: bert-base-uncased
  num_of_labels: 5
  learning_rate: 0.001
  batch_size: 16
  epochs: 2
sk_params:
  clf:
    lr__C:
    - 0.1
    - 1.0
    - 10.0
    nb__alpha:
    - 0.1
    - 0.5
    - 1.0
    voting:
    - hard
    - soft
  vectorizer:
    max_df:
    - 0.5
    - 0.75
    - 1.0
    min_df:
    - 1
    - 2
    - 3
    ngram_range:
    - - 1
      - 1
    - - 1
      - 2
    - - 1
      - 3
