sk_params:
  vectorizer:
    max_df: [0.5, 0.75, 1.0]
    ngram_range: [[1, 1], [1, 2], [1, 3]]
    min_df: [1, 2, 3]
  clf:
    voting: ['hard', 'soft']
    nb__alpha: [0.1, 0.5, 1.0]
    lr__C: [0.1, 1.0, 10.0]
bert_params:
  model_name_or_path: huawei-noah/TinyBERT_General_4L_312D
  num_of_labels: 3
  learning_rate: 0.001
  batch_size: 16
  epochs: 2
  gradient_accumulation_steps: 4


